package jp.co.fbsc.salessupport.model;

import java.math.BigDecimal;
import java.util.Date;

public class TOrderManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.order_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.instruction_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String instructionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.rebalance_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String rebalanceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.base_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String baseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.portfolio_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String portfolioCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.asset_category_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String assetCategoryCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.asset_category_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String assetCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.model_type_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String modelTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.model_type_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String modelTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.portfolio_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String portfolioStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.nyu_shutsu_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private BigDecimal nyuShutsuAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.operation_start_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String operationStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.rebalance_target_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String rebalanceTargetKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.asset_class_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String assetClassCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.asset_class_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String assetClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.product_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String productCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.product_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.sell_buy_quantity
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private BigDecimal sellBuyQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.order_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.instruction_create_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String instructionCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.sell_buy_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String sellBuyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.trade_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String tradeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.delivery_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String deliveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.sell_buy_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String sellBuyKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.execute_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String executeKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.instruction_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String instructionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.cash_short
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String cashShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.instruction_error
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String instructionError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.allocation_ratio_estranged
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String allocationRatioEstranged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.order_file
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String orderFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.out_instruction_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String outInstructionFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.delete_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.create_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.create_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.update_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private Date updateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_order_manage.update_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    private String updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.order_no
     *
     * @return the value of public.t_order_manage.order_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.order_no
     *
     * @param orderNo the value for public.t_order_manage.order_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.instruction_no
     *
     * @return the value of public.t_order_manage.instruction_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getInstructionNo() {
        return instructionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.instruction_no
     *
     * @param instructionNo the value for public.t_order_manage.instruction_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setInstructionNo(String instructionNo) {
        this.instructionNo = instructionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.rebalance_no
     *
     * @return the value of public.t_order_manage.rebalance_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getRebalanceNo() {
        return rebalanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.rebalance_no
     *
     * @param rebalanceNo the value for public.t_order_manage.rebalance_no
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setRebalanceNo(String rebalanceNo) {
        this.rebalanceNo = rebalanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.base_date
     *
     * @return the value of public.t_order_manage.base_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getBaseDate() {
        return baseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.base_date
     *
     * @param baseDate the value for public.t_order_manage.base_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setBaseDate(String baseDate) {
        this.baseDate = baseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.portfolio_cd
     *
     * @return the value of public.t_order_manage.portfolio_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getPortfolioCd() {
        return portfolioCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.portfolio_cd
     *
     * @param portfolioCd the value for public.t_order_manage.portfolio_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setPortfolioCd(String portfolioCd) {
        this.portfolioCd = portfolioCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.asset_category_cd
     *
     * @return the value of public.t_order_manage.asset_category_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getAssetCategoryCd() {
        return assetCategoryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.asset_category_cd
     *
     * @param assetCategoryCd the value for public.t_order_manage.asset_category_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setAssetCategoryCd(String assetCategoryCd) {
        this.assetCategoryCd = assetCategoryCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.asset_category_name
     *
     * @return the value of public.t_order_manage.asset_category_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getAssetCategoryName() {
        return assetCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.asset_category_name
     *
     * @param assetCategoryName the value for public.t_order_manage.asset_category_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setAssetCategoryName(String assetCategoryName) {
        this.assetCategoryName = assetCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.model_type_cd
     *
     * @return the value of public.t_order_manage.model_type_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getModelTypeCd() {
        return modelTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.model_type_cd
     *
     * @param modelTypeCd the value for public.t_order_manage.model_type_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setModelTypeCd(String modelTypeCd) {
        this.modelTypeCd = modelTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.model_type_name
     *
     * @return the value of public.t_order_manage.model_type_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getModelTypeName() {
        return modelTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.model_type_name
     *
     * @param modelTypeName the value for public.t_order_manage.model_type_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setModelTypeName(String modelTypeName) {
        this.modelTypeName = modelTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.portfolio_status
     *
     * @return the value of public.t_order_manage.portfolio_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getPortfolioStatus() {
        return portfolioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.portfolio_status
     *
     * @param portfolioStatus the value for public.t_order_manage.portfolio_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setPortfolioStatus(String portfolioStatus) {
        this.portfolioStatus = portfolioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.nyu_shutsu_amount
     *
     * @return the value of public.t_order_manage.nyu_shutsu_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public BigDecimal getNyuShutsuAmount() {
        return nyuShutsuAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.nyu_shutsu_amount
     *
     * @param nyuShutsuAmount the value for public.t_order_manage.nyu_shutsu_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setNyuShutsuAmount(BigDecimal nyuShutsuAmount) {
        this.nyuShutsuAmount = nyuShutsuAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.operation_start_date
     *
     * @return the value of public.t_order_manage.operation_start_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getOperationStartDate() {
        return operationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.operation_start_date
     *
     * @param operationStartDate the value for public.t_order_manage.operation_start_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setOperationStartDate(String operationStartDate) {
        this.operationStartDate = operationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.rebalance_target_kbn
     *
     * @return the value of public.t_order_manage.rebalance_target_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getRebalanceTargetKbn() {
        return rebalanceTargetKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.rebalance_target_kbn
     *
     * @param rebalanceTargetKbn the value for public.t_order_manage.rebalance_target_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setRebalanceTargetKbn(String rebalanceTargetKbn) {
        this.rebalanceTargetKbn = rebalanceTargetKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.asset_class_cd
     *
     * @return the value of public.t_order_manage.asset_class_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getAssetClassCd() {
        return assetClassCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.asset_class_cd
     *
     * @param assetClassCd the value for public.t_order_manage.asset_class_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setAssetClassCd(String assetClassCd) {
        this.assetClassCd = assetClassCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.asset_class_name
     *
     * @return the value of public.t_order_manage.asset_class_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getAssetClassName() {
        return assetClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.asset_class_name
     *
     * @param assetClassName the value for public.t_order_manage.asset_class_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setAssetClassName(String assetClassName) {
        this.assetClassName = assetClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.product_cd
     *
     * @return the value of public.t_order_manage.product_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.product_cd
     *
     * @param productCd the value for public.t_order_manage.product_cd
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.product_name
     *
     * @return the value of public.t_order_manage.product_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.product_name
     *
     * @param productName the value for public.t_order_manage.product_name
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.sell_buy_quantity
     *
     * @return the value of public.t_order_manage.sell_buy_quantity
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public BigDecimal getSellBuyQuantity() {
        return sellBuyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.sell_buy_quantity
     *
     * @param sellBuyQuantity the value for public.t_order_manage.sell_buy_quantity
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setSellBuyQuantity(BigDecimal sellBuyQuantity) {
        this.sellBuyQuantity = sellBuyQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.order_amount
     *
     * @return the value of public.t_order_manage.order_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.order_amount
     *
     * @param orderAmount the value for public.t_order_manage.order_amount
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.instruction_create_date
     *
     * @return the value of public.t_order_manage.instruction_create_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getInstructionCreateDate() {
        return instructionCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.instruction_create_date
     *
     * @param instructionCreateDate the value for public.t_order_manage.instruction_create_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setInstructionCreateDate(String instructionCreateDate) {
        this.instructionCreateDate = instructionCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.sell_buy_date
     *
     * @return the value of public.t_order_manage.sell_buy_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getSellBuyDate() {
        return sellBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.sell_buy_date
     *
     * @param sellBuyDate the value for public.t_order_manage.sell_buy_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setSellBuyDate(String sellBuyDate) {
        this.sellBuyDate = sellBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.trade_date
     *
     * @return the value of public.t_order_manage.trade_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.trade_date
     *
     * @param tradeDate the value for public.t_order_manage.trade_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.delivery_date
     *
     * @return the value of public.t_order_manage.delivery_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.delivery_date
     *
     * @param deliveryDate the value for public.t_order_manage.delivery_date
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.sell_buy_kbn
     *
     * @return the value of public.t_order_manage.sell_buy_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getSellBuyKbn() {
        return sellBuyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.sell_buy_kbn
     *
     * @param sellBuyKbn the value for public.t_order_manage.sell_buy_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setSellBuyKbn(String sellBuyKbn) {
        this.sellBuyKbn = sellBuyKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.execute_kbn
     *
     * @return the value of public.t_order_manage.execute_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getExecuteKbn() {
        return executeKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.execute_kbn
     *
     * @param executeKbn the value for public.t_order_manage.execute_kbn
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setExecuteKbn(String executeKbn) {
        this.executeKbn = executeKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.instruction_status
     *
     * @return the value of public.t_order_manage.instruction_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getInstructionStatus() {
        return instructionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.instruction_status
     *
     * @param instructionStatus the value for public.t_order_manage.instruction_status
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setInstructionStatus(String instructionStatus) {
        this.instructionStatus = instructionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.cash_short
     *
     * @return the value of public.t_order_manage.cash_short
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getCashShort() {
        return cashShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.cash_short
     *
     * @param cashShort the value for public.t_order_manage.cash_short
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setCashShort(String cashShort) {
        this.cashShort = cashShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.instruction_error
     *
     * @return the value of public.t_order_manage.instruction_error
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getInstructionError() {
        return instructionError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.instruction_error
     *
     * @param instructionError the value for public.t_order_manage.instruction_error
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setInstructionError(String instructionError) {
        this.instructionError = instructionError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.allocation_ratio_estranged
     *
     * @return the value of public.t_order_manage.allocation_ratio_estranged
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getAllocationRatioEstranged() {
        return allocationRatioEstranged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.allocation_ratio_estranged
     *
     * @param allocationRatioEstranged the value for public.t_order_manage.allocation_ratio_estranged
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setAllocationRatioEstranged(String allocationRatioEstranged) {
        this.allocationRatioEstranged = allocationRatioEstranged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.order_file
     *
     * @return the value of public.t_order_manage.order_file
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getOrderFile() {
        return orderFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.order_file
     *
     * @param orderFile the value for public.t_order_manage.order_file
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setOrderFile(String orderFile) {
        this.orderFile = orderFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.out_instruction_flg
     *
     * @return the value of public.t_order_manage.out_instruction_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getOutInstructionFlg() {
        return outInstructionFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.out_instruction_flg
     *
     * @param outInstructionFlg the value for public.t_order_manage.out_instruction_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setOutInstructionFlg(String outInstructionFlg) {
        this.outInstructionFlg = outInstructionFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.delete_flg
     *
     * @return the value of public.t_order_manage.delete_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.delete_flg
     *
     * @param deleteFlg the value for public.t_order_manage.delete_flg
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.create_dt
     *
     * @return the value of public.t_order_manage.create_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.create_dt
     *
     * @param createDt the value for public.t_order_manage.create_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.create_user_id
     *
     * @return the value of public.t_order_manage.create_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.create_user_id
     *
     * @param createUserId the value for public.t_order_manage.create_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.update_dt
     *
     * @return the value of public.t_order_manage.update_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.update_dt
     *
     * @param updateDt the value for public.t_order_manage.update_dt
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_order_manage.update_user_id
     *
     * @return the value of public.t_order_manage.update_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_order_manage.update_user_id
     *
     * @param updateUserId the value for public.t_order_manage.update_user_id
     *
     * @mbg.generated Thu Jun 06 21:37:49 ICT 2024
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }
}